#!/bin/bash

#
# Puts the sample component into the development directory.
#
# $1 is the name of the component.
# $2 is the $GLU_HOME directory
#

#
# This is the Java version of the placement script
#

name="$1"
GLU_HOME="$2"

LANGUAGE="Java"
LANGUAGE_ENDING=".java"
LANGUAGES_SRC="$GLU_HOME/languages/java/src"
GLU_SRC="$GLU_HOME/src/java"
SAMPLE_COMPONENT_NAME="SampleComponent"

"$GLU_HOME"/bin/generic_placement "$name" "$GLU_HOME" "$LANGUAGE" "$LANGUAGE_ENDING" "$LANGUAGES_SRC" "$GLU_SRC" "$SAMPLE_COMPONENT_NAME"

